name: 'test'
on:
  schedule:
    - cron: '13 18 * * *'

jobs:
  jd_comment_crawler:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@2
      - name: 'Setup python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests 
      - name: 'Run script'
        run: python jd_comments.py
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PWD}}
          subject: 'jd comments'
          body: 'file//a.log'
          to: ${{ secrets.TO }}
          from: ${{secrets.MAIL_USERNAME}}
          #content_type: text/html

      

